name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Build the extension
        run: yarn build
      - name: Archive extension
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
