name: Release Workflow

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  VITE_PLAUSIBLE_API_HOST: ${{ vars.VITE_PLAUSIBLE_API_HOST }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Create tag based on date
        uses: peter-evans/create-pull-request@v3
        with:
          branch: tag-branch
          commit-message: Create tag based on date
          title: Create tag based on date
          body: Please merge this branch to create a new tag based on date
          script: |
            # 获取当前的日期，格式为YYYY-MM-DD
            DATE=$(date +%F)
            # 生成一个基于日期的标签，前缀为v
            TAG="v$DATE"
            # 检查这个标签是否已经存在，如果不存在，就创建并推送这个标签
            if ! git rev-parse "$TAG" >/dev/null 2>&1; then
              git tag "$TAG"
              git push origin "$TAG"
            fi
  build:
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Setup yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Package
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: chathub.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: chathub.zip
