name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Setup corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Build the extension
        run: yarn build
      # 显示dist目录的内容
      - name: Show dist directory
        run: echo "dist directory:" && ls dist
      # 修改path参数的值
      - name: Archive extension
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
